### RECUPERAR TODAS LAS PELICULAS
GET http://localhost:1234/movies


### RECUPERAR UNA PELICULA POR ID
GET http://localhost:1234/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf


### RECUPERAR UNA PELICULA POR GENERO
GET http://localhost:1234/movies?genre=drama


### CREAR UNA PELICULA con datos faltantes

POST http://localhost:1234/movies
Content-Type: application/json

{
  "title": 1,
  "year": "pepe"  
  
}


### CREAR UNA PELICULA
POST http://localhost:1234/movies
Content-Type: application/json

{
  "title": "The Godfather",
  "year": 1975,
  "director": "Francis Ford Coppola",
  "duration": 175,
  "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
  "genre": [
    "Crime",
    "Drama"
  ]
}

### actualizar una pelicula
PATCH  http://localhost:1234/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf
Content-Type: application/json

{
    "year": 1993
}

### Borrar una pelicula
DELETE   http://localhost:1234/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf
